### Numpy full form is numerical python

In [2]:
!python3 -m pip install numpy

In [3]:
!pip3 install --upgrade pip

In [4]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5,])
print(a)

[1 2 3 4 5]


In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [8]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [10]:
np.full((2,3),7)

array([[7, 7, 7],
       [7, 7, 7]])

In [11]:
np.eye(3) #idenctical matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.random.rand(3,2)

array([[0.39386287, 0.51332406],
       [0.12156191, 0.73504298],
       [0.91860907, 0.28685794]])

In [13]:
np.random.randint(10,50,(3,2))

array([[49, 16],
       [29, 27],
       [37, 12]])

### Array Properties

In [14]:
a = np.array([[1,2,3,4],[4,5,6,7]])
print(a)  #always look to the starting brackets to know which dimenstion array 

[[1 2 3 4]
 [4 5 6 7]]


In [15]:
print(a.ndim) #number of dimensions
print(a.shape) #number of rows and coloumns
print(a.size) #number of elements
print(a.dtype) #data types of the elements

2
(2, 4)
8
int64


### Reshaping and flattening

In [16]:
a.reshape(4,2) #reshape array

array([[1, 2],
       [3, 4],
       [4, 5],
       [6, 7]])

In [17]:
a.flatten() #convert multi dimension array into 1D array

array([1, 2, 3, 4, 4, 5, 6, 7])

### Index and sliceing

In [18]:
a = np.array([10,20,30,40,50])

In [19]:
#to find array from index
print(a[0]) #frist element
print(a[1:4])
print(a[-1]) #last element

10
[20 30 40]
50


In [20]:
b = np.array([[1,2,3],[4,5,6]])

In [21]:
print(b[0]) #first row
print(b[0,1]) # 1 row 2nd column

[1 2 3]
2


### Mathematical Opretion - element wise opretion

In [22]:
x= np.array([1,2,3,4,5])
y= np.array([4,5,6,7,8])

In [23]:
print(x+y)
print(x-y)
print(x*y)

[ 5  7  9 11 13]
[-3 -3 -3 -3 -3]
[ 4 10 18 28 40]


### Aggregation functions

In [24]:
print(np.sum(a))
print(np.mean(a))
print(np.max(a))
print(np.min(a))
print(np.std(a))
print(np.var(a))

150
30.0
50
10
14.142135623730951
200.0


In [25]:
print(b)

[[1 2 3]
 [4 5 6]]


In [26]:
np.sum(b, axis=0) #coloum wise opration

array([5, 7, 9])

In [27]:
np.sum(b, axis=1) #row wise opration

array([ 6, 15])

In [28]:
a=15
b=30
c=a+b
print(c)

45


In [29]:
# Write a code to give grades to students on there marks
 